### ISSUE TITLE
demos\button issues

### ISSUE THREAD

**Issue by xoviat** [vecty-components/material#27]
`MarkupIfNotNil` needs to be fixed - disabled because of some issue with checkbox

```
panic: ValueOf: invalid value
wasm_exec.js:51 
wasm_exec.js:51 goroutine 1 [running]:
wasm_exec.js:51 syscall/js.ValueOf({0x22ea0, 0x40a2a0})
wasm_exec.js:51 	C:/Program Files/Go/src/syscall/js/js.go:219 +0xfb
wasm_exec.js:51 syscall/js.Value.Set({{}, 0x7ff80001000000e1, 0x411d20}, {0x30181, 0x15}, {0x22ea0, 0x40a2a0})
wasm_exec.js:51 	C:/Program Files/Go/src/syscall/js/js.go:314 +0x8
wasm_exec.js:51 github.com/hexops/vecty.wrappedObject.Set({{{}, 0x7ff80001000000e1, 0x411d20}}, {0x30181, 0x15}, {0x22ea0, 0x40a2a0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom_js.go:106 +0x18
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileProperties(0x4a8d20, 0x4af810)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:266 +0x34
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x4a8d20, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:218 +0x47
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0x56670, 0x462900}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:51 github.com/hexops/vecty.render({0xa85bb8, 0x462900}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x48b180, 0x4aff78)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x48b180, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.render({0x558c0, 0x48b180}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x48b260, 0x4b0488)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x48b260, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.render({0x558c0, 0x48b260}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x4a8c40, 0x4b09e0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.KeyedList.reconcile({0x4a8c40, {0x0, 0x0}}, 0x4a57a0, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:727 +0x33
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x4a57a0, 0x4b0e90)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:419 +0x14c
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x4a57a0, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0x566e0, 0x444140}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0x56b08, 0x434230}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1049 +0x4d
wasm_exec.js:51 github.com/hexops/vecty.render({0xa85a28, 0x434230}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x48a000, 0x4b16a0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x48a000, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.render({0x558c0, 0x48a000}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x48a0e0, 0x4b1bb0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x48a0e0, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0x56a60, 0x4243c0}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:51 github.com/hexops/vecty.renderIntoNode({0x2d7bc, 0xa}, {0x57e38, 0x40e630}, {0x56a60, 0x4243c0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1238 +0xa
wasm_exec.js:51 github.com/hexops/vecty.RenderBody({0x56a60, 0x4243c0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1190 +0x1a
wasm_exec.js:51 main.main()
wasm_exec.js:51 	~/workspace/material/demos/demos.go:30 +0x6
```

**Comment by VinceJnz** [comment]
I can't figure out how to get any of it working now.
Am I able to compile button.go to a wasm and add an index file with the appropriate html to test button or do I have to do something else?

**Comment by xoviat** [comment]
```
git clone https://bitbucket.org/xoviat/gaepher.git
cd gaepher
go install
```


```
cd demos
```


```
gaepher serve
```

Where are you failing?

**Comment by xoviat** [comment]
Note: the move to gaepher is to take out the html and js files.

**Comment by VinceJnz** [comment]
Okay, I was trying to use it the same way as before. I'll take a look at gaepher.
One question is would this make it more difficult for others to adapt the examples to their own projects?

**Comment by xoviat** [comment]
I don't know how others are doing things, but the way I use vecty (and this is a vecty project) is to serve the same `main.wasm` file for all urls aside from (`/assets` and `/api`) urls (the internal client router handles not found).

> One question is would this make it more difficult for others to adapt the examples to their own projects?

`index.html` and `wasm_exec.js` are required for any project using vecty (the only alternative is to compile using gopherjs, which has much more limited support and does not work on windows). What is gaepher doing?

- Running `GOARCH=wasm GOOS=js go build`
- Serving up the `wasm_exec.js` from the local go installation
- Serving up the `index.html` file below:

```html
<!DOCTYPE html>
<head>
	<script src="/wasm_exec.js"></script>
	<script>
		(async () => {
			const resp = await fetch('/{{.WASMFile}}');
			if (!resp.ok) {
				const pre = document.createElement('pre');
				pre.innerText = await resp.text();
				document.body.appendChild(pre);
				return;
			}
			const src = await resp.arrayBuffer();
			const go = new Go();
			const result = await WebAssembly.instantiate(src, go.importObject);
			go.run(result.instance);
		})();
	</script>
</head>
<body>
	<span style="position: absolute;top: 50%; left: 50%;transform: translate(-50%, -50%)">
		<img src="data:image/png;base64,{{.LoaderImage}}" alt="loader.gif">
	</span>
</body>
```

There is some other stuff that gaepher does for my personal use (mainly integrating with Google App Engine), but there is no unique content (other than the loader image) that's served by gaepher. In fact gaepher is not open for contributions because it should no nothing more than serve up the users app. 

In fact, there is another project that I want to get working with ci called [wasmbrowsertest](https://github.com/agnivade/wasmbrowsertest) that pretty much does the same thing: [`index.html`](https://github.com/agnivade/wasmbrowsertest/blob/master/handler.go#L93), `wasm_exec.js` (from the local installation), and `main.wasm`. In fact I copied this functionality into gaepher (which was an existing tool that I already had for other similar purposes) to add this functionality. So I don't think I'm imposing my own model, merely following the standard that others are doing but making it easier on the developer.

**Comment by VinceJnz** [comment]
It all sounds reasonable, and good point about it being a vecty project.

**Comment by VinceJnz** [comment]
All good now. :-)
I should have read the readme file.

**Comment by VinceJnz** [comment]
When I run this up with gaepher serve as per your instructions and navigate to the buttons everything seems to work.
I don't have any errors in the browser console.

I have remove the comment // from the following lines and this seems to work.
```
			c.newBtn(
				&button.B{
					Label: vecty.Text("Icon"),
					Icon: &icon.I{ // was commented out
						Name: "favorite", // was commented out
					}, // was commented out
```

**Comment by xoviat** [comment]
The button issue is that these lines are commented out:

https://github.com/vecty-material/material/blob/3dc8411dc59bb151b337227853f706f01ba9d9ff/base/tools.go#L43-L46

If you uncomment these lines, you get the error. Obviously, checking the location before running a function is a hack.

**Comment by VinceJnz** [comment]
Only the buttons that use ripple cause the crash so the problem seems to be something to do with ripple.

If you put the `tools.go` line back in 
https://github.com/vecty-material/material/blob/7c4f1a6e9d18c2255274f1bf070aaa8293e38df6/base/tools.go#L41-L48

It will run if you disable ripple by forcing `applyRipple = false` in the following function:
https://github.com/vecty-material/material/blob/7c4f1a6e9d18c2255274f1bf070aaa8293e38df6/demos/button/button_demo.go#L123-L127


The output from `func r(...)` is used for the `Root: vecty.Markup( r(Ripple) )` value in a `button.B`
It appears that there is something incorrect with the `vecty.Applyer' that `func r(...)' produces.

**Comment by VinceJnz** [comment]
After a lot of poking around the cause of the problem seems to be this line:
https://github.com/vecty-material/material/blob/0b286c267aaeedf3a3a6424c4a49ee7b6d307434/ripple/ripple.go#L23
Contained in the following function 
https://github.com/vecty-material/material/blob/0b286c267aaeedf3a3a6424c4a49ee7b6d307434/ripple/ripple.go#L15
Note: `c.(type) = *ripple.R`
<br>
The following function accepts `value interface{}`
`func vecty.Property(key string, value interface{}) vecty.Applyer`

This `value` eventually gets input into the function `js.ValueOf(x interface{})`
```
// ValueOf returns x as a JavaScript value:
//
//  | Go                     | JavaScript             |
//  | ---------------------- | ---------------------- |
//  | js.Value               | [its value]            |
//  | js.Func                | function               |
//  | nil                    | null                   |
//  | bool                   | boolean                |
//  | integers and floats    | number                 |
//  | string                 | string                 |
//  | []interface{}          | new array              |
//  | map[string]interface{} | new object             |
//
// Panics if x is not one of the expected types.
```

The problem is that `c.(type) = *ripple.R`
This causes `VauleOf()` to panic

I tried changing 
`vecty.Property("vecty-material-ripple", c).Apply(h)`
to
`vecty.Property("vecty-material-ripple", c.R.Component()).Apply(h)`

The button demo was able to run but I don't think the ripple effect was working.

Also it appears that here has been some problem with `func (c *R) Apply(h *vecty.HTML)` in the past as there are a number of lines commented out.

**Comment by xoviat** [comment]
@VinceJnz very nice! I think there are just a few things left.

**Comment by xoviat** [comment]
working

**Comment by VinceJnz** [comment]
@xoviat is the ripple effect actually working?
