### ISSUE TITLE
demos\checkbox issues

### ISSUE THREAD

**Issue by xoviat** [vecty-components/material#28]
When 'with JS' boxes are clicked

```
panic: vecty: Rerender invoked on Component that has never been rendered
wasm_exec.js:51 
wasm_exec.js:51 goroutine 6 [running]:
wasm_exec.js:51 github.com/hexops/vecty.Rerender({0x44390, 0x460180})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:810 +0x10
wasm_exec.js:51 main.makeIndeterminateButton.func1(0x460680, 0x431e80)
wasm_exec.js:51 	~/workspace/material/demos/checkbox/checkbox_demo.go:296 +0x4
wasm_exec.js:51 github.com/vecty-material/material/button.(*B).onClick(...)
wasm_exec.js:51 	~/workspace/material/button/button.go:88
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileProperties.func1({0x45398, 0x496650}, {0x496630, 0x1, 0x1})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:246 +0x1f
wasm_exec.js:51 github.com/hexops/vecty.funcOf.func1({{}, 0x7ff8000100000128, 0x4928b0}, {0x496620, 0x1, 0x1})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom_js.go:60 +0x10
wasm_exec.js:51 syscall/js.handleEvent()
wasm_exec.js:51 	C:/Program Files/Go/src/syscall/js/func.go:96 +0x27
```

**Comment by VinceJnz** [comment]
I started looking at the checkbox demo and couldn't work out where the problem was. I'm a bit busy over the next week or 2 but after that I have time to take a look at some issues.

**Comment by xoviat** [comment]
I reworked the demos to be compatible with my development tool, which significantly speeds up development. Feedback welcome, and you should now have write access to this repository (master is protected, so no force push). Don't hesitate to merge  something that you think makes sense.

**Comment by xoviat** [comment]
Actually, checkbox is now working completely (fixed in #42). There is an issue with button though currently suppressed by these lines (again, see in #42):

```golang
		// todo: enable this for all paths
		if js.Global().Get("window").Get("location").Get("pathname").String() == "/checkbox" {
			return vecty.MarkupIf(rootMarkup != nil, *rootMarkup)
		}
```

See the button issue (#27) for the problem; it needs to be fixed.

**Comment by VinceJnz** [comment]
Thanks, I take a look. I'm relatively new to working with git/github so I appoligize in advance if it takes me a while to figure out how to work with this.

**Comment by xoviat** [comment]
working
